title: Donovan Webb # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student at Maynooth University 
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/donovanWebb">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
